version: 2.1
executors:
  medium_executor:
    docker:
      - image: circleci/openjdk:11.0.4-jdk-stretch
    resource_class: medium
    working_directory: ~/project
    environment:
      JAVA_TOOL_OPTIONS: -Xmx2g
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2

commands:
  prepare:
    description: "Prepare"
    steps:
      - checkout
      - restore_cache:
          name: Restore cached gradle dependencies
          keys:
            - deps2-{{ checksum "build.gradle" }}-{{ .Branch }}-{{ .Revision }}
            - deps2-{{ checksum "build.gradle" }}
            - deps2-
  capture_test_results:
    description: "Capture test results"
    steps:
      - store_test_results:
          path: build/test-results

jobs:
  build:
    executor: medium_executor
    steps:
      - prepare
      - run:
          name: Assemble
          command: |
            ./gradlew --no-daemon --parallel build sourcesJar
      - save_cache:
          name: Caching gradle dependencies
          key: deps2-{{ checksum "build.gradle" }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - .gradle
            - ~/.gradle
      - capture_test_results
      - store_artifacts:
            path: build/libs
      - persist_to_workspace:
            root: ~/project
            paths:
              - ./

  publish:
    executor: medium_executor
    steps:
      - prepare
      - attach_workspace:
          at: ~/project
      - run:
          name: Publish
          command: |
            ./gradlew --no-daemon --parallel publish

workflows:
  version: 2
  circleci:
    jobs:
      - build:
          filters:
            tags: &filters-release-tags
              only: /^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?/
      - publish:
          filters:
            branches:
              only:
                - master
                - /^release-.*/
            tags:
              <<: *filters-release-tags
          requires:
            - build
          context:
            - cloudsmith-protocols
